# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildDockerImages
    steps:
    - task: DockerCompose@0
      displayName: 'Build and Push Docker Images'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerComposeFile: 'docker-compose.yml'
        action: 'Build service images'

- stage: Deploy
  jobs:
  - job: DeployToVM
    steps:
    - task: SSH@0
      displayName: 'Deploy to Azure VM'
      inputs:
        sshEndpoint: 'testing'
        runOptions: 'commands'
        commands: |
          cd /path/to/your/app
          git pull origin main
          docker-compose down
          docker-compose up -d
