version: '3.8'

services:
  # Backend Service
  api:
    image: bhandarenakul/sproutly-test:backend-latest-$(Build.SourceVersion)  # Pull image from Docker Hub
    container_name: sproutly-api
    networks:
      - sproutly-network
    expose:
      - "8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000

  # Frontend Service
  frontend:
    image: bhandarenakul/sproutly-test:frontend-latest-$(Build.SourceVersion)  # Pull image from Docker Hub
    container_name: sproutly-frontend
    ports:
      - "3000:3000"
    networks:
      - sproutly-network
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://sproutly-api:8000  # Backend URL for frontend

  # Nginx Reverse Proxy
  # Nginx Service (acting as reverse proxy)
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Link custom Nginx configuration
    networks:
      - sproutly-network
    depends_on:
      - frontend
      - api

networks:
  sproutly-network:
    driver: bridge
