name: Create Weekly Issues

on:
  schedule:
    - cron: "0 12 * * 5" # Runs every Friday at 12:00 UTC
  workflow_dispatch: # Allows manual triggering

permissions:
  issues: write  # Ensure write permissions to create issues

jobs:
  create-issue:
    runs-on: ubuntu-22.04
    steps:
      - name: Create weekly issue
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "[User Story] - Sprint Demo",
              body: "### Epic Link:\n\n#17\n\n### User Story\n\nAs a Client, I want to see the weekly progress, so that I can give fast feedback.\n\n### Task Links:"
            });
